Repository epignosis/gnosis, pull requests merged in 2022-02, with the labels that each got.

#69 chore: update color palette
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  src/components/Drawer/components/styles.ts
  src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButton.test.tsx.snap
  src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Result/__snapshots__/Result.test.tsx.snap
  src/theme/default/Colors.stories.tsx
  src/theme/default/colors.ts
  src/theme/default/config/button.ts
  src/theme/default/config/card.ts
  src/theme/default/config/drawer.ts
  src/theme/default/config/formElements.ts
  src/theme/default/config/modal.ts
  src/theme/default/config/progressBar.ts
Labels: chore

#82 chore: change remaining icons
  src/icons/bell_slash.svg
  src/icons/bell_solid.svg
  src/icons/edit.svg
  src/icons/edit_table.svg
  src/icons/export_data.svg
  src/icons/grip_lines.svg
  src/icons/import_data.svg
  src/icons/index.ts
  src/icons/trash_alt.svg
  src/icons/unit_failed.svg
  src/icons/vertical_ellipsis.svg
Labels: chore

#85 fix(checkbox): checkbox partially selected and omitted label
  src/components/FormElements/CheckboxGroup/Checkbox.stories.tsx
  src/components/FormElements/CheckboxGroup/Checkbox.tsx
  src/components/FormElements/CheckboxGroup/__tests__/Checkbox.test.tsx
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/FormElements/CheckboxGroup/styles.ts
  src/icons/ellipsis.svg
  src/icons/index.ts
Labels: fix

#86 style: minor fixes on svgs
  src/icons/paperclip.svg
  src/icons/sorting_arrows_ascending.svg
  src/icons/sorting_arrows_descending.svg
Labels: chore

#87 feat: add disabled functionality on Input, Textarea and Select
  src/components/FormElements/Input/Input.stories.tsx
  src/components/FormElements/Input/Input.test.tsx
  src/components/FormElements/Input/Input.tsx
  src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
  src/components/FormElements/Input/styles.ts
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.test.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Textarea/Textarea.stories.tsx
  src/components/FormElements/Textarea/Textarea.test.tsx
  src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/components/FormElements/styles.ts
  src/theme/default/config/formElements.ts
Labels: feature
