Repository epignosis/gnosis, pull requests merged in 2022-03, with the labels that each got.

#90 chore: update dependencies
  .eslintrc.json
  .storybook/main.js
  package-lock.json
  package.json
  src/components/Alert/Alert.test.tsx
  src/components/AspectRatio/AspectRatio.test.tsx
  src/components/Avatar/Avatar.test.tsx
  src/components/Badge/Badge.test.tsx
  src/components/Breadcrumb/Breadcrumb.test.tsx
  src/components/Button/Button.test.tsx
  src/components/Card/Card.test.tsx
  src/components/Chip/Chip.test.tsx
  src/components/Drawer/Drawer.test.tsx
  src/components/FormElements/CheckboxGroup/__tests__/Checkbox.test.tsx
  src/components/FormElements/CheckboxGroup/__tests__/CheckboxGroup.test.tsx
  src/components/FormElements/FormError/FormError.test.tsx
  src/components/FormElements/Input/Input.test.tsx
  src/components/FormElements/InputError/InputError.test.tsx
  src/components/FormElements/Label/Label.test.tsx
  src/components/FormElements/RadioButtonGroup/__tests__/RadioButton.test.tsx
  src/components/FormElements/RadioButtonGroup/__tests__/RadioButtonGroup.test.tsx
  src/components/FormElements/RadioGroup/__tests__/Radio.test.tsx
  src/components/FormElements/RadioGroup/__tests__/RadioGroup.test.tsx
  src/components/FormElements/Select/Select.test.tsx
  src/components/FormElements/Textarea/Textarea.test.tsx
  src/components/Grid/Grid.test.tsx
  src/components/Heading/Heading.test.tsx
  src/components/Modal/Modal.test.tsx
  src/components/ProgressBar/ProgressBar.test.tsx
  src/components/Result/Result.test.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tag/Tag.test.tsx
  src/components/Text/Text.test.tsx
  src/components/Tooltip/Tooltip.test.tsx
Labels: chore

#91 feat(modal / tabs): new api and features for modal and tabs components
  src/components/FormElements/RadioGroup/RadioGroup.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Sidebar/NavHandle.tsx
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/TabsContent.tsx
  src/components/Tabs/TabsNavItem.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tabs/styles.ts
  src/icons/files_icon.svg
Labels: feature

#92 test(checkboxgroup): fix CheckboxGroup tests
  src/components/FormElements/CheckboxGroup/__tests__/CheckboxGroup.test.tsx
Labels: fix

#93 chore: drop-down icon on Select component
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
Labels: chore
