Repository epignosis/gnosis, pull requests merged in 2022-01, with the labels that each got.

#73 chore!: remove Toaster component
  package-lock.json
  package.json
  src/components/Toaster/Toaster.stories.tsx
  src/components/Toaster/Toaster.test.tsx
  src/components/Toaster/Toaster.tsx
  src/components/Toaster/styles.ts
  src/index.ts
Labels: chore

#75 feat!: new pagination component
  package-lock.json
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/Pagination/styles.ts
  src/components/Pagination/usePagination.ts
  src/theme/default/config/index.ts
  src/theme/default/config/pagination.ts
  src/theme/default/defaultTheme.ts
Labels: feature

#76 chore!: remove toaster component
  package-lock.json
  package.json
  src/components/Toaster/Toaster.stories.tsx
  src/components/Toaster/Toaster.test.tsx
  src/components/Toaster/Toaster.tsx
  src/components/Toaster/styles.ts
  src/index.ts
Labels: chore

#77 build(semantic-release): enable beta branch and release
  .github/workflows/cd.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  release.config.js
Labels: chore

#78 fix(semantic-release): added conventional commits changelog
  .gitignore
  package-lock.json
  package.json
Labels: fix

#71 chore: Badge component finetuning
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.test.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/components/Badge/styles.ts
  src/theme/default/config/badge.ts
Labels: chore

#80 chore: make sidebar title jsx element or sting
  src/components/Sidebar/NavItem.tsx
Labels: chore

#81 ci(storybook): storybook site build configuration
  .github/workflows/release.yml
  release.config.js
Labels: build-ci
