Repository epignosis/gnosis, pull requests merged in 2022-12, with the labels that each got.

#115 style: styling changes on sidebar
  src/components/Loaders/Loader.tsx
  src/components/Loaders/__snapshots__/Loader.test.tsx.snap
  src/components/Loaders/styles.ts
  src/components/Sidebar/NavHandle.tsx
  src/components/Sidebar/NavItem.tsx
  src/components/Sidebar/Sidebar.stories.tsx
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
  src/components/Sidebar/styles.ts
  src/icons/calendar.svg
  src/icons/catalog.svg
  src/icons/chat_clouds.svg
  src/icons/hamburger.svg
  src/icons/hand_holding_magic.svg
  src/icons/home.svg
  src/icons/index.ts
  src/icons/my_courses.svg
  src/icons/opened_message.svg
  src/icons/person_from_portal.svg
Labels: chore

#116 feat: RTL support
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Alert/__snapshots__/Alert.test.tsx.snap
  src/components/Alert/styles.ts
  src/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/components/Badge/styles.ts
  src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/components/Breadcrumb/styles.ts
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/styles.ts
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/styles.ts
  src/components/Chip/__snapshots__/Chip.test.tsx.snap
  src/components/Chip/styles.ts
  src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  src/components/Drawer/components/styles.ts
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/FormElements/CheckboxGroup/styles.ts
  src/components/FormElements/FormError/__snapshots__/FormError.test.tsx.snap
  src/components/FormElements/FormError/styles.ts
  src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
  src/components/FormElements/Input/styles.ts
  src/components/FormElements/InputError/__snapshots__/InputError.test.tsx.snap
  src/components/FormElements/InputError/styles.ts
  src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButton.test.tsx.snap
  src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/components/FormElements/RadioButtonGroup/styles.ts
  src/components/FormElements/RadioGroup/__tests__/__snapshots__/Radio.test.tsx.snap
  src/components/FormElements/RadioGroup/__tests__/__snapshots__/RadioGroup.test.tsx.snap
  src/components/FormElements/RadioGroup/styles.ts
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/components/FormElements/styles.ts
  src/components/Modal/Modal.stories.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/Pagination/styles.ts
  src/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  src/components/ProgressBar/styles.ts
  src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
  src/components/Sidebar/styles.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tabs/styles.ts
  src/components/Tag/__snapshots__/Tag.test.tsx.snap
  src/components/Tag/styles.ts
Labels: feature

#120 refactor(mediaplayer component): remove video player styling
  src/components/Loaders/Loader.tsx
  src/components/Loaders/__snapshots__/Loader.test.tsx.snap
  src/components/Loaders/styles.ts
  src/components/MediaPlayer/VideoPlayer/VideoPlayer.tsx
  src/components/MediaPlayer/VideoPlayer/styles.ts
Labels: refactor
