Repository epignosis/gnosis, pull requests merged in 2023-11, with the labels that each got.

#241 refactor(dropdown.tsx): expand dropdown functionality
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/helpers.tsx
  src/components/Dropdown/types.ts
Labels: refactor

#253 feat(dropdown): fix placement
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/helpers.tsx
  src/components/Dropdown/types.ts
Labels: feature

#255 fix(dropdown): fix placement issues
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/styles.ts
  src/components/Dropdown/types.ts
Labels: fix

#256 fix(paginationSelector.tsx): Add listPlacement prop
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/Pagination/components/PaginationSelector.tsx
  src/components/Pagination/components/styles.ts
  src/components/Pagination/types.ts
Labels: chore

#257 fix(pagination.tsx): Add listPlacement to page size selector
  src/components/Pagination/Pagination.tsx
Labels: chore

#258 fix: rename link button class
  src/components/Button/Button.tsx
  src/components/Button/styles.ts
Labels: fix

#260 Feat/allow jsx in tooltip and handle readonly
  src/components/FormElements/CheckboxGroup/Checkbox.tsx
  src/components/FormElements/CheckboxGroup/styles.ts
  src/components/FormElements/Input/Input.stories.tsx
  src/components/FormElements/Input/Input.tsx
  src/components/FormElements/RadioGroup/Radio.tsx
  src/components/FormElements/RadioGroup/styles.ts
Labels: feature

#265 style(return if list open on dropdown): return if list open on dropdown
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/types.ts
Labels: chore

#266 fix(input): allow arrow up and arrow down keys in number input
  src/components/FormElements/Input/helpers.ts
Labels: fix
