Repository epignosis/gnosis, pull requests merged in 2023-12, with the labels that each got.

#269 fix(radio, checkbox): fix styles and readonly property
  src/components/FormElements/CheckboxGroup/Checkbox.tsx
  src/components/FormElements/RadioGroup/Radio.tsx
  src/components/FormElements/RadioGroup/__tests__/__snapshots__/Radio.test.tsx.snap
  src/components/FormElements/RadioGroup/__tests__/__snapshots__/RadioGroup.test.tsx.snap
  src/components/FormElements/RadioGroup/styles.ts
Labels: fix

#267 refactor: select has search if options > 10
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/data.ts
Labels: chore

#270 fix: fix default inner search for select when having grouped options
  src/components/FormElements/Select/Select.tsx
Labels: fix

#274 feat(dropdown): add disabled state
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/styles.ts
  src/components/Dropdown/types.ts
  src/theme/default/config/dropdown.ts
Labels: feature
