Repository epignosis/gnosis, pull requests merged in 2023-07, with the labels that each got.

#172 fix: apply reversed sorting in a column
  src/components/Table/Table.stories.tsx
  src/components/Table/__tests__/Table.test.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/Header.tsx
  src/components/Table/types.ts
Labels: fix

#173 fix: optionally enable interactive tooltip
  src/components/Table/Table.stories.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Tooltip/Tooltip.tsx
Labels: fix

#178 fix: overflow on chips
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/__snapshots__/Chip.test.tsx.snap
  src/components/Chip/helpers.ts
  src/components/Chip/styles.ts
Labels: fix

#180 Refactor Tabs
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/TabsNavItem.tsx
Labels: refactor

#186 style(label.tsx): finetuning on label inline styles
  src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
  src/components/FormElements/Input/styles.ts
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/components/FormElements/styles.ts
  src/icons/audio.svg
Labels: chore
