Repository epignosis/gnosis, pull requests merged in 2023-10, with the labels that each got.

#230 fix(button): noGutters styles for buttons with icons
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/styles.ts
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: fix

#231 refactor(body.tsx): add className on Body.tsx on Card component
  src/components/Card/Body.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
Labels: refactor

#235 fix(dropdown): scroll to list bottom on open
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
Labels: fix

#239 chore: revert overflow logic
  src/components/Dropdown/Dropdown.tsx
Labels: chore

#238 refactor(dropdown.tsx): add emptyStateText prop
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/types.ts
Labels: refactor

#240 refactor(dropdown.tsx): Add placeholderText prop for Dropdown search input
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/types.ts
Labels: refactor
