Repository epignosis/gnosis, pull requests merged in 2023-09, with the labels that each got.

#199 fix : Select component improvements
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/data.ts
  src/components/FormElements/Select/styles.ts
Labels: fix

#201 fix: primary button colours
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/styles.ts
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/theme/default/config/button.ts
Labels: fix

#202 style(select.tsx): add color and background when navigating through options with keyboard
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/theme/default/config/formElements.ts
Labels: chore

#203 style(Select.tsx): change the focused color on select
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
Labels: chore

#205 style(button.tsx): update ghost buttons danger and success
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/styles.ts
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/theme/default/config/button.ts
Labels: chore

#207 refactor(select.tsx): introduce async select
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/helpers.tsx
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: feature

#208 fix: centering tooltip arrow
  src/components/Chip/__snapshots__/Chip.test.tsx.snap
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/styles.ts
Labels: fix

#209 fix: interactive tooltip fix
  src/components/Tooltip/Tooltip.tsx
Labels: fix

#210 fix(result): add border to Result component
  src/components/Result/Result.stories.tsx
  src/components/Result/Result.tsx
  src/components/Result/__snapshots__/Result.test.tsx.snap
  src/components/Result/styles.ts
  src/theme/default/config/result.ts
Labels: fix

#218 fix: minor fix in select styles
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
Labels: fix

#220 fix(tag): styles and theme fixes
  src/components/Tag/__snapshots__/Tag.test.tsx.snap
  src/components/Tag/styles.ts
  src/theme/default/config/tag.ts
Labels: fix
