Repository epignosis/gnosis, pull requests merged in 2024-11, with the labels that each got.

#455 chore(icons): add icon for simple dashboard learner view
  src/icons/client/party-horn.svg
  src/icons/index.ts
Labels: chore

#456 chore(result): add jsx.element as possible type of info property and update stories
  src/components/Result/Result.stories.tsx
  src/components/Result/Result.tsx
Labels: chore

#460 fix(select.tsx): fix select nested options
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/components/CustomOptionComponent.tsx
  src/components/FormElements/Select/helpers.tsx
  src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
Labels: fix

#462 chore(cards): remove shadows from cards
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/styles.ts
Labels: chore

#461 chore(icons): add ai icons
  src/icons/feature/ai/ai-loader.svg
  src/icons/feature/ai/coins.svg
  src/icons/feature/ai/sparkles-solid.svg
  src/icons/index.ts
Labels: chore

#463 chore(anchor element): underline anchor tag
  src/theme/utils/global.ts
Labels: chore

#467 chore(add new page icon): add new page icon
  src/icons/index.ts
  src/icons/legacy/page.svg
Labels: chore

#470 chore(course view icon): add course view icon
  src/icons/index.ts
  src/icons/legacy/course-view.svg
Labels: chore

#471 chore(icons): add star svg with no viewbox
  src/icons/client/group-view.svg
  src/icons/client/star-no-viewbox.svg
  src/icons/index.ts
Labels: chore

#473 feat(modal): add modal sizes
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/styles.ts
Labels: feature

#475 chore(icons): add paypal card svg
  src/icons/client/paypal-card.svg
  src/icons/index.ts
Labels: chore
