Repository epignosis/gnosis, pull requests merged in 2024-09, with the labels that each got.

#391 chore(tooltip): add parent props for custom props
  src/components/Tooltip/Tooltip.tsx
Labels: chore

#392 Long Custom User Fields Cut Off on Signup Screen
  src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
  src/components/FormElements/Label/__snapshots__/Label.test.tsx.snap
  src/components/FormElements/Label/styles.ts
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: fix

#390 build(add a11y tool at gnosis): add a11y tool
  .storybook/main.js
  package-lock.json
  package.json
Labels: chore

#395 chore(select): minor type change
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/types.ts
Labels: chore

#394 feat(select): apply tooltip on selected values
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/components/CustomMultiValueLabel.tsx
  src/components/FormElements/Select/components/CustomSingleValue.tsx
  src/components/FormElements/Select/styles.ts
Labels: feature

#396 chore(select): turn string into jsx
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: chore

#398 chore(table): empty headings should be "td" for accessibility reasons
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/Header.tsx
  src/components/Table/styles.ts
Labels: chore

#397 Update card thumbnail styles
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/styles.ts
Labels: chore

#400 chore(trigger release): trigger release action
  src/components/Card/Card.stories.tsx
Labels: chore

#401 Fix: menuIsOpen prop on select
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/icons/client/hourglass-end.svg
  src/icons/index.ts
Labels: bug

#403 feat: add tooltipIcon to Input and tooltipContent to DropdownItem
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/types.ts
  src/components/FormElements/Input/Input.tsx
Labels: feature

#407 chore(icon): add numbered list icon
  src/icons/client/numbered-list.svg
  src/icons/index.ts
Labels: chore

#404 chore(select): remove inner search
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/components/CustomOptionComponent.tsx
  src/components/FormElements/Select/components/CustomValueContainer.tsx
  src/components/FormElements/Select/constants.ts
  src/components/FormElements/Select/data.ts
  src/components/FormElements/Select/helpers.tsx
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: chore

#410 chore(icons): update number list svg to accept color
  src/icons/client/numbered-list.svg
Labels: chore

#411 feat(select): props change
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/helpers.tsx
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: feature

#412 chore(icons): add more icon with no viewbox
  src/icons/feature/units/index.ts
  src/icons/feature/units/more-icon-no-viewbox.svg
Labels: chore

#413 chore(icons): export icon from index
  src/icons/index.ts
Labels: chore

#415 fix(a11y toggle description color): description color changes
  src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
  src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
  src/components/FormElements/ToggleSwitch/styles.ts
  src/theme/default/config/formElements.ts
Labels: fix

#416 chore(result): add a heading level option
  src/components/Result/Result.tsx
  src/components/Result/__snapshots__/Result.test.tsx.snap
  src/components/Result/styles.ts
  src/theme/default/config/result.ts
Labels: chore
