Repository epignosis/gnosis, pull requests merged in 2024-04, with the labels that each got.

#313 add development release workflow
  .github/workflows/deploy_staging.yml
Labels: build-ci

#315 chore: add data-testids in checkbox and tetxtarea label
  src/components/FormElements/CheckboxGroup/Checkbox.tsx
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
  src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/FormElements/Textarea/Textarea.tsx
  src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: chore

#319 chore(icons): add custom report icon
  src/icons/client/custom-reports.svg
  src/icons/index.ts
Labels: chore

#321 chore(icons): add circle play solid icon
  src/icons/client/circle-play-solid.svg
  src/icons/index.ts
Labels: chore

#322 feat(icon): add an icon for course store
  src/icons/client/course-store.svg
  src/icons/index.ts
Labels: feature

#324 chore(new icons): added new icons
  src/icons/arrows/arrow-down-large.svg
  src/icons/arrows/arrow-down.svg
  src/icons/arrows/index.ts
  src/icons/client/pencil-brush.svg
  src/icons/client/rocket.svg
  src/icons/index.ts
Labels: chore

#325 chore(icons): replace lock icon
  src/icons/client/icon-lock.svg
Labels: chore

#327 chore(icons): add rating icons
  src/icons/feature/rating/Icons.stories.tsx
  src/icons/feature/rating/index.ts
  src/icons/feature/rating/rating-excellent.svg
  src/icons/feature/rating/rating-good.svg
  src/icons/feature/rating/rating-okay.svg
  src/icons/feature/rating/rating-poor.svg
  src/icons/index.ts
Labels: chore

#330 chore(icons): add circle arrow up and down icons
  src/icons/arrows/circle-arrow-down.svg
  src/icons/arrows/circle-arrow-up.svg
  src/icons/arrows/index.ts
Labels: chore
