Repository epignosis/gnosis, pull requests merged in 2024-08, with the labels that each got.

#376 feat(select): improvements
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMenuList.tsx
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: feature

#377 fix(table): pass unique id to avoid bug
  src/components/Table/components/Header.tsx
Labels: bug

#378 fix(checkbox): add unique id's
  src/components/Table/components/Body.tsx
  src/components/Table/components/TableRow.tsx
Labels: bug

#379 chore: add ai icons for eve
  src/icons/index.ts
  src/icons/legacy/ai-assistant-icon.svg
  src/icons/legacy/ai-message-icon.svg
Labels: chore

#382 chore(tooltip): added a new parentRole prop for accessibility
  src/components/Tooltip/Tooltip.tsx
Labels: chore

#383 feat: select option tooltip
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomOption.tsx
  src/components/FormElements/Select/data.ts
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: feature

#388 chore(tabs): fix accessibility issues
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/TabsContent.tsx
  src/components/Tabs/TabsNavItem.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tabs/styles.ts
Labels: chore

#389 chore: add wand icon
  src/icons/index.ts
  src/icons/legacy/wand-icon.svg
Labels: chore
