Repository epignosis/gnosis, pull requests merged in 2024-06, with the labels that each got.

#345 chore(dropdown): add a title attribute to dropdown list items
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: chore

#347 chore(icon): add submission icon for assignments
  src/icons/client/assignments/submission.svg
  src/icons/index.ts
Labels: chore

#349 fix(table): use onMouseMove to potentially fix hover bug
  src/components/Table/components/TableRow.tsx
Labels: fix

#350 fix(table): onMouseEnter
  src/components/Table/components/TableRow.tsx
Labels: fix

#355 chore(icons): replace icons
  src/icons/client/calendar-users.svg
  src/icons/client/house-user.svg
  src/icons/feature/units/classroom-large.svg
  src/icons/feature/units/index.ts
  src/icons/feature/units/online-meeting-large.svg
  src/icons/index.ts
Labels: chore

#357 chore(icon): minor change
  src/icons/client/assignments/submission.svg
Labels: chore

#358 chore(icons.tsx): add radio selected filled svg
  src/icons/index.ts
  src/icons/legacy/radio-selected-filled.svg
Labels: chore

#359 chore(icons.tsx): radio icon filled stroke color
  src/icons/legacy/radio-selected-filled.svg
Labels: chore

#360 chore(icons.tsx): add unit pending filled svg
  src/icons/index.ts
  src/icons/legacy/unit-pending-filled.svg
Labels: chore

#361 chore(icons.tsx) add referral icons
  src/icons/client/referral/referral-claimable.svg
  src/icons/client/referral/referral-claimed.svg
  src/icons/client/referral/referral-dance.svg
  src/icons/client/referral/referral-pending.svg
  src/icons/client/referral/referral-time.svg
  src/icons/client/referral/referral.svg
  src/icons/index.ts
Labels: chore

#363 Revert "chore(icons.tsx) add referral icons (#361)"
  src/icons/client/referral/referral-claimable.svg
  src/icons/client/referral/referral-claimed.svg
  src/icons/client/referral/referral-dance.svg
  src/icons/client/referral/referral-pending.svg
  src/icons/client/referral/referral-time.svg
  src/icons/client/referral/referral.svg
  src/icons/index.ts
Labels: chore

#364 chore: add referral icons
  src/icons/client/referral/referral-claimable.svg
  src/icons/client/referral/referral-claimed.svg
  src/icons/client/referral/referral-dance.svg
  src/icons/client/referral/referral-pending.svg
  src/icons/client/referral/referral-time.svg
  src/icons/client/referral/referral.svg
  src/icons/index.ts
Labels: chore

#365 feat: add ai icon to legacy icons
  src/icons/index.ts
  src/icons/legacy/ai-icon.svg
Labels: feature
