Repository epignosis/gnosis, pull requests merged in 2024-02, with the labels that each got.

#297 refactor(tabs): added data-testids
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/TabsNavItem.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: chore

#298 refactor(table): added data-testids
  src/components/Table/Table.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/Header.tsx
Labels: chore

#299 feat(loader): implement clip loader
  src/components/Loaders/Loader.stories.tsx
  src/components/Loaders/Loader.tsx
Labels: feature

#300 feat(dropdown): adjust menu position when there is not available space
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
Labels: bug

#304 chore(pagination): add some missing test ids
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: chore

#305 chore(Button.tsx): add small button size
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/styles.ts
Labels: chore
