Repository epignosis/gnosis, pull requests merged in 2024-10, with the labels that each got.

#421 feat: upgrade react version
  src/components/Card/Drawer.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
Labels: feature

#422 feat: upgrade gnosis react
  .github/workflows/deploy_staging.yml
  .github/workflows/release.yml
Labels: feature

#423 feat(videoplayer): remove lazy import
  package-lock.json
  package.json
  src/components/Alert/Alert.stories.tsx
  src/components/MediaPlayer/AudioPlayer/AudioPlayer.tsx
  src/components/MediaPlayer/MediaPlayer.tsx
  src/components/MediaPlayer/VideoPlayer/VideoPlayer.tsx
  src/components/MediaPlayer/VideoPlayer/types.ts
Labels: fix

#424 fix: remove media player from storybook
  package-lock.json
  package.json
  src/components/MediaPlayer/AudioPlayer/AudioPlayer.tsx
  src/components/MediaPlayer/MediaPlayer.stories.tsx
  src/components/MediaPlayer/MediaPlayer.tsx
  src/components/MediaPlayer/VideoPlayer/VideoPlayer.tsx
  src/components/MediaPlayer/VideoPlayer/types.ts
  src/index.ts
Labels: chore

#426 chore: add extra reverse trial icons
  src/icons/client/microchip-ai.svg
  src/icons/client/passport.svg
  src/icons/index.ts
Labels: chore

#432 chore(icons): add lock/unlock solid icons, modify text box icon for reverse trial
  src/icons/client/icon-lock-solid.svg
  src/icons/client/lock-open-solid.svg
  src/icons/client/text-box.svg
  src/icons/index.ts
Labels: chore

#429 feat(statustag): introduced a new status tag component
  src/components/StatusTag/StatusTag.stories.tsx
  src/components/StatusTag/StatusTag.test.tsx
  src/components/StatusTag/StatusTag.tsx
  src/components/StatusTag/styles.ts
  src/index.ts
  src/theme/default/config/index.ts
  src/theme/default/config/statusTag.ts
  src/theme/default/defaultTheme.ts
Labels: feature

#434 chore(select.tsx): modify component to accept aria label
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.test.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
Labels: chore

#435 chore(status tag): change red base to dark red for A11y puproses
  src/theme/default/config/statusTag.ts
Labels: chore

#433 chore(select): a11y on tooltips
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/components/CustomMultiValueLabel.tsx
  src/components/FormElements/Select/components/CustomOptionComponent.tsx
  src/components/FormElements/Select/components/CustomSingleValue.tsx
Labels: chore

#438 chore(status tag): convert status tag colors to union
  src/components/StatusTag/StatusTag.tsx
Labels: chore

#443 Add craft icons to gnosis
  src/icons/index.ts
  src/icons/legacy/change-tone.svg
  src/icons/legacy/magic-wand.svg
  src/icons/legacy/translate.svg
Labels: chore

#444 chore(icons): add arrow right icon
  src/icons/arrows/arrow-right.svg
  src/icons/arrows/index.ts
Labels: chore

#436 feat(breadcrumbs): add new breadcrumbs implementation
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/styles.ts
  src/index.ts
  src/theme/default/config/breadcrumbs.ts
  src/theme/default/config/index.ts
  src/theme/default/defaultTheme.ts
Labels: feature

#441 feat(input): add onIconClick
  src/components/FormElements/Input/Input.stories.tsx
  src/components/FormElements/Input/Input.tsx
  src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
  src/components/FormElements/Input/styles.ts
Labels: feature

#447 chore(card.tsx): Add hasShadow and hasBorder props, and change the hover bg color
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/styles.ts
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/styles.ts
  src/theme/default/config/card.ts
Labels: chore

#450 fix(breadcrumbs): fix arrows on RTL dirction
  src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: fix

#453 chore(icons.tsx): add icons for card footer
  src/icons/client/assignments/not-passed-answer.svg
  src/icons/client/assignments/passed-answer.svg
  src/icons/client/canceled-filled.svg
  src/icons/client/start-arrow-filled.svg
  src/icons/index.ts
Labels: chore

#451 chore: add onclick at StatusTag
  src/components/StatusTag/StatusTag.tsx
Labels: chore

#454 fix: status tag args
  src/components/StatusTag/StatusTag.stories.tsx
Labels: fix
