Repository epignosis/gnosis, pull requests merged in 2024-05, with the labels that each got.

#332 feat(select): add count options for inner search as prop
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/types.ts
Labels: feature

#335 fix(dropdown): fix wrapper issues
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/styles.ts
Labels: bug, fix

#337 feat(card): ability to manipulate card hover
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
Labels: feature

#338 fix(toggle switch): accept internal icon and size fix
  src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
  src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
  src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
  src/components/FormElements/ToggleSwitch/styles.ts
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tabs/styles.ts
Labels: fix

#340 chore(icons): add sparkles icon
  src/icons/client/credits.svg
  src/icons/client/sparkles.svg
  src/icons/index.ts
Labels: chore

#341 chore(icons): remove duplicate, add new
  src/icons/actions/addition-event.svg
  src/icons/actions/index.ts
  src/icons/client/square-add.svg
  src/icons/feature/questions/index.ts
  src/icons/feature/units/classroom-large.svg
  src/icons/feature/units/index.ts
  src/icons/feature/units/online-meeting-large.svg
  src/icons/index.ts
Labels: chore

#343 feat(icon): add scroll indicator icon
  src/icons/client/scroll-indicator-icon.svg
  src/icons/index.ts
Labels: feature

#344 chore(icons): update icons
  src/icons/client/BranchesDropdown.svg
  src/icons/index.ts
Labels: released
