Repository epignosis/gnosis, pull requests merged in 2024-01, with the labels that each got.

#275 chore(select): add tooltip content to Select component
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: chore

#268 fix: validating new input values on select component
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/types.ts
Labels: fix

#278 fix: Select component duplicate values and no options message
  src/components/FormElements/Select/Select.stories.tsx
  src/components/FormElements/Select/Select.tsx
  src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
  src/components/FormElements/Select/styles.ts
  src/components/FormElements/Select/types.ts
Labels: fix

#279 fix: table auto hide styles
  src/components/Table/Table.stories.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/styles.ts
Labels: fix

#281 fix(table): reset selected rows when unmounting
  src/components/Table/Table.tsx
Labels: bug

#282 fix(select): improve indicator
  src/components/FormElements/Select/Select.tsx
Labels: fix

#280 perf(table): create separate tableRow component
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/components/Body.tsx
  src/components/Table/components/Cell.tsx
  src/components/Table/components/Header.tsx
  src/components/Table/components/TableRow.tsx
  src/components/Table/constants.ts
  src/components/Table/reducer.ts
  src/components/Table/types.ts
Labels: performance

#287 fix(table): row click triggered from row selection
  src/components/Table/Table.stories.tsx
  src/components/Table/components/Cell.tsx
  src/components/Table/components/TableRow.tsx
Labels: fix

#288 perf(table): more changes to improve perfomance
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/DataCells.tsx
  src/components/Table/components/Header.tsx
  src/components/Table/components/TableRow.tsx
  src/components/Table/types.ts
  src/index.ts
Labels: performance

#289 fix(datacell): remove extra char
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/DataCells.tsx
Labels: fix

#290 feat(progressbar): add label and color properties
  src/components/ProgressBar/ProgressBar.stories.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  src/components/ProgressBar/styles.ts
  src/theme/default/config/progressBar.ts
Labels: feature

#294 feat(table): new imperative handler to reset selected rows
  src/components/Table/Table.tsx
  src/components/Table/constants.ts
  src/components/Table/reducer.ts
  src/components/Table/types.ts
Labels: feature

#295 fix(table): missing type
  src/components/Table/types.ts
Labels: chore

#296 chore(button): button primary darker colour
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/types.ts
  src/theme/default/config/button.ts
Labels: chore
