Repository epignosis/gnosis, pull requests merged in 2024-07, with the labels that each got.

#367 chore(typography): export typescales
  src/index.ts
  src/theme/utils/typography.ts
Labels: chore

#368 Chore/clean up components
  src/components/AspectRatio/AspectRatio.stories.tsx
  src/components/Breadcrumb/Breadcrumb.stories.tsx
  src/components/Breadcrumb/Breadcrumb.test.tsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/components/Breadcrumb/styles.ts
  src/components/Card/AspectRatio/AspectRatio.test.tsx
  src/components/Card/AspectRatio/AspectRatio.tsx
  src/components/Card/AspectRatio/__snapshots__/AspectRatio.test.tsx.snap
  src/components/Card/AspectRatio/styles.ts
  src/components/Card/Header.tsx
  src/index.ts
  src/theme/default/TypographyDocs.stories.tsx
  src/theme/default/config/breadcrumb.ts
  src/theme/default/config/index.ts
  src/theme/default/defaultTheme.ts
Labels: chore, clean-up

#366 feat: add data-testids for table row cells
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/components/DataCells.tsx
Labels: feature

#369 Chore: add data-testids to Result body component
  src/components/Result/Result.tsx
  src/components/Result/__snapshots__/Result.test.tsx.snap
Labels: chore

#370 ci(release.yml): add workflow dispatch
  .github/workflows/release.yml
Labels: chore, build-ci

#371 chore(icons): change import data icon
  src/icons/client/import-data.svg
  src/icons/index.ts
  src/icons/legacy/import-data.svg
Labels: chore

#372 chore(icons): linkedin logo icon
  src/icons/index.ts
  src/icons/legacy/linkedin-icon.svg
  src/icons/social/index.ts
  src/icons/social/linkedin-logo.svg
Labels: chore

#373 chore(icons): replace linkedin logo icon
  src/icons/social/linkedin-logo.svg
Labels: chore

#374 chore(icons): google tag manager icon
  src/icons/index.ts
  src/icons/logos/google-tag-manager.svg
  src/icons/logos/index.ts
Labels: chore

#375 chore: add circle play icon for consensus
  src/icons/client/circle-play.svg
  src/icons/index.ts
Labels: chore
