Repository epignosis/gnosis, pull requests merged in 2025-03, with the labels that each got.

#513 refactor(dropdown): create list item and list item title components
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/components/DropdownListItem.tsx
  src/components/Dropdown/components/DropdownListItemTitle.tsx
  src/components/Dropdown/components/styles.ts
  src/components/Dropdown/helpers.tsx
  src/components/Dropdown/styles.ts
  src/components/FormElements/Input/SearchInput.tsx
Labels: refactor

#515 chore: add cliboard action icons
  src/components/FormElements/Input/helpers.ts
  src/icons/actions/clipboard-check.svg
  src/icons/actions/clipboard-cross.svg
  src/icons/actions/index.ts
  src/icons/index.ts
Labels: chore

#516 chore: update attendance icons
  src/icons/actions/clipboard-check.svg
  src/icons/actions/clipboard-cross.svg
Labels: chore

#518 chore(modal.tsx): fix button broken styles
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/styles.ts
Labels: chore

#521 feat(table): add option to toggle multiple rows
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/components/Table/constants.ts
  src/components/Table/reducer.ts
  src/components/Table/types.ts
  src/icons/feature/verticalStepper/complete-dot.svg
  src/icons/feature/verticalStepper/complete-step-with-gradient.svg
  src/icons/feature/verticalStepper/complete-step.svg
  src/icons/feature/verticalStepper/incomplete-dot.svg
  src/icons/feature/verticalStepper/incomplete-step.svg
  src/icons/feature/verticalStepper/partial-step.svg
  src/icons/index.ts
  tsconfig.json
Labels: feature

#523 chore(icons): update lti svg
  src/icons/logos/lti-tool.svg
Labels: chore
