Repository epignosis/gnosis, pull requests merged in 2025-07, with the labels that each got.

#563 chore(icons): add linkedin circle icon
  src/icons/client/index.ts
  src/icons/client/linkedin-circle.svg
Labels: chore

#565 feat(table): add support for row persistence
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/components/Header.tsx
  src/components/Table/components/TableRow.tsx
  src/components/Table/types.ts
Labels: feature

#568 perf(table): prevent unnecessary rerendering due to rows or collumns …
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.tsx
  src/components/Table/components/Header.tsx
  src/components/Table/components/TableRow.tsx
  src/components/Table/types.ts
Labels: performance

#570 fix(table): fix hover issue
  src/components/Table/Table.tsx
  src/components/Table/reducer.ts
Labels: fix
